version: '3.8'

services:
  app:
    container_name: API
    build: .
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
      MONGODB_URI: ${MONGODB_URI}
    depends_on:
      - mongo

  mongo:
    container_name: MongoDB
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
