version: '3.8'

services:
  app:
    container_name: API
    build: .
    env_file:
      - .env.prod
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      NODE_ENV: production
      PORT: ${API_PORT}
      AUTH_SECRET: ${AUTH_SECRET}
      MONGODB_URL: ${MONGODB_URL}
    depends_on:
      - mongo

  mongo:
    container_name: MongoDB
    image: mongo:latest
    ports:
      - "27017:27017"
    env_file:
      - .env.prod
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
